# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class K9s < Formula
  desc "Kubernetes CLI To Manage Your Clusters In Style!"
  homepage "https://k9scli.io/"
  version "0.30.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/derailed/k9s/releases/download/v0.30.0/k9s_Darwin_arm64.tar.gz"
      sha256 "0b88ea4fec9ebc977579aefdeeae366702daea4798591cf4aa1de0f222ed207f"

      def install
        bin.install "k9s"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/derailed/k9s/releases/download/v0.30.0/k9s_Darwin_amd64.tar.gz"
      sha256 "e038eb6be9fe08815c73338518d5b76717329b720ca6fec546ce665c09b6a1ae"

      def install
        bin.install "k9s"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/derailed/k9s/releases/download/v0.30.0/k9s_Linux_arm64.tar.gz"
      sha256 "5cd65aed9209e7acebede7af8d675d3df355977c27d62efa43d7701623229605"

      def install
        bin.install "k9s"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/derailed/k9s/releases/download/v0.30.0/k9s_Linux_amd64.tar.gz"
      sha256 "42b267380d32387e837f920d8313494a2098833d4b083477c40da216fb89dabf"

      def install
        bin.install "k9s"
      end
    end
  end

  test do
    system "k9s version"
  end
end
